language: java

script: "./gradlew dist"

install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: UmNNj0bmB2JZG8k18TbmgSOERcLLSzLUVxNdyip0Ydt1C76vt8QgujKrzIgZzqOcPQLUPwnBIoKSo2/2gN4Ret+NlMGH/TNHqb91A4fJmSIjuAEXzJx1fJFwZYqVBy26EL/jFWUhhebq7izNF/do+Q8ZOqdVW9Q1BXEcYKMmgVE=
  skip_cleanup: true
  file:
    - build/distributions/xmlcalabash1-metadata-extractor-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
